version: '3.8'
services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: benchmark_development
    ports:
      - "5432:5432"
    volumes:
      -  ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
